### ISSUE TITLE
error install

### ISSUE THREAD

**Issue by mikrotickets** [yandinovriandi/TunnelMikrotikBot#2]
![Screenshot_134](https://user-images.githubusercontent.com/63126121/195926203-5c3c25d6-ab37-40b0-8154-b1cf04f85be2.png)

**Comment by mikrotickets** [comment]
the solution was to update node js

**Comment by yandinovriandi** [comment]
try only npm install

**Comment by yandinovriandi** [comment]
> the solution was to update node js
try `npm install` not use `npm run build`

**Comment by yandinovriandi** [comment]
update you'r node

**Comment by yandinovriandi** [comment]
> the solution was to update node js

yes, you must update you'r node js
